iac:
  name: infrastructure_as_code_app
  version: 1.0
  cloud:
    provider: aws
    properties:
      region: us-east-2
      action: create
      features:
        rds:
          identifier: db-testing
          storage: 40
          insttype: db.t2.micro
          engine: mysql
          username: admin
          password: password123!
          name: db_test
          retention: 7