iac:
  name: infrastructure_as_code_app
  version: 1.0
  cloud:
    provider: aws
    properties:
      region: us-east-2
      action: create
      features:
        vpc:
          cidrblock: 10.0.0.0/16
          subnet:
            cidrblock: 10.0.1.0/24
            avzone: us-east-2a